version: '3.8'

services:

  python_tests:
    build:
      context: ./src/python
      dockerfile: Dockerfile
    container_name: python_tests
    volumes:
      - ./tests:/tests
      - ./results:/results
    entrypoint: ./run_tests.sh

  javascript_tests:
    build:
      context: ./src/javascript
      dockerfile: Dockerfile
    container_name: javascript_tests
    volumes:
      - ./tests:/tests
      - ./results:/results
    entrypoint: ./run_tests.sh

  typescript_tests:
    build:
      context: ./src/typescript
      dockerfile: Dockerfile
    container_name: typescript_tests
    volumes:
      - ./tests:/tests
      - ./results:/results
    entrypoint: ./run_tests.sh
  